apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ tpl .Values.resource.default.name . }}-psp
  labels:
    {{- include "hello-world-app.labels" . | nindent 4 }}
spec:
  allowPrivilegeEscalation: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 1000
  runAsUser:
    rule: MustRunAsNonRoot
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 1000
        max: 1000
  volumes:
  - secret
  - emptyDir
