apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ tpl .Values.resource.default.name . }}-role
  labels:
    {{- include "hello-world-app.labels" . | nindent 4 }}
rules:
- apiGroups: ['extensions', 'policy']
  resources: ['podsecuritypolicies']
  resourceNames:
  - {{ tpl .Values.resource.default.name . }}-psp
  verbs: ['use']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ tpl .Values.resource.default.name . }}-role-binding
  labels:
    {{- include "hello-world-app.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .Values.resource.default.name . }}-service-account
    namespace: {{ tpl .Values.resource.default.name . }}
roleRef:
  kind: Role
  name: {{ tpl .Values.resource.default.name . }}-role
  apiGroup: rbac.authorization.k8s.io
