apiVersion: v1
kind: Service
metadata:
  name: {{ tpl .Values.resource.default.name . }}-service
  labels:
    {{- include "hello-world-app.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 8080
    protocol: TCP
  selector:
    {{- include "hello-world-app.selectorLabels" . | nindent 4 }}
