apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: {{ tpl .Values.resource.default.name . }}-psp
  labels:
    app: {{ tpl .Values.resource.default.name . }}
spec:
  privileged: false
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  runAsUser:
    rule: MustRunAsNonRoot
    ranges:
      - min: 1
        max: 65535
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
    - 'configMap'
    - 'secret'
  allowPrivilegeEscalation: false
  hostNetwork: false
  hostIPC: false
  hostPID: false
