version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - piontec
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - python
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - piontec
    open-pull-requests-limit: 1
